version: "3"

volumes:
  db-store:

services:
  php:
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./:/app:cached

  db:
    build:
      context: ./docker/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-wishlist}
      - MYSQL_USER=${DB_USERNAME:-shizuoka}
      - MYSQL_PASSWORD=${DB_PASSWORD:-fujiyama}
      - MYSQL_ROOT_PASSWORD=root
    platform: linux/amd64

  web:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - php
    volumes:
      - ./:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /app/.git
      - /app/docker